version: "3"

services:
  nats_producer:
    build: ./nats_streaming
    command: /app/natsclient -nats nats:4223 -cluster test-cluster -producer
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - nats
      - jaeger
  nats_consumer:
    build: ./nats_streaming
    command: /app/natsclient -nats nats:4223 -cluster test-cluster
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - nats_producer
      - jaeger
  http_client:
    build: ./http_call
    command: /app/httpopentracing -producer -server http://http_server:8080
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
      - http_server
  http_server:
    build: ./http_call
    command: /app/httpopentracing
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
  nats:
    image: nats-streaming
    command: -p 4223 -m 8223 -D -store file -dir /tmp --file_sync=false
    ports: 
      - 8223:8223
  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  
